//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Web.Services.WebServiceAttribute(Namespace="https://t-mobile.racowireless.com/SMSRicochet1.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="ReceiveSoap", Namespace="https://t-mobile.racowireless.com/SMSRicochet1.0")]
public abstract partial class Receive : System.Web.Services.WebService {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://t-mobile.racowireless.com/SMSRicochet1.0/ReceiveSMS", RequestNamespace="https://t-mobile.racowireless.com/SMSRicochet1.0", ResponseNamespace="https://t-mobile.racowireless.com/SMSRicochet1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public abstract ServiceResult ReceiveSMS(string securityKey, string from, string message);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://t-mobile.racowireless.com/SMSRicochet1.0/Test", RequestNamespace="https://t-mobile.racowireless.com/SMSRicochet1.0", ResponseNamespace="https://t-mobile.racowireless.com/SMSRicochet1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public abstract ServiceResult Test(string securityKey);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://t-mobile.racowireless.com/SMSRicochet1.0")]
public enum ServiceResult {
    
    /// <remarks/>
    ACCEPTED,
    
    /// <remarks/>
    MESSAGE_TOO_LONG,
    
    /// <remarks/>
    INVALID_CREDENTIALS,
    
    /// <remarks/>
    REJECTED,
    
    /// <remarks/>
    NOTFOUND,
    
    /// <remarks/>
    INVALID_RECIPIENT,
}
